"""add multimodal message fields

Revision ID: 1e5ccdf3ba81
Revises: ef130fc18c17
Create Date: 2026-05-28 17:55:54.010289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e5ccdf3ba81'
down_revision: Union[str, Sequence[str], None] = 'ef130fc18c17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('caption', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('enhanced_image', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('generated_audio', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('transcript', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('emotion', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('tones', sa.JSON(), nullable=True))
    op.add_column('messages', sa.Column('retrieved_context', sa.JSON(), nullable=True))
    op.drop_constraint(op.f('users_patient_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'relationship_type')
    op.drop_column('users', 'patient_id')
    op.drop_column('users', 'profile_picture')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('relationship_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_patient_id_fkey'), 'users', 'users', ['patient_id'], ['id'])
    op.drop_column('messages', 'retrieved_context')
    op.drop_column('messages', 'tones')
    op.drop_column('messages', 'emotion')
    op.drop_column('messages', 'transcript')
    op.drop_column('messages', 'generated_audio')
    op.drop_column('messages', 'enhanced_image')
    op.drop_column('messages', 'caption')
    # ### end Alembic commands ###
