"""added admin table

Revision ID: 1e81f3f1c86c
Revises: 21355cefc333
Create Date: 2026-05-23 02:00:37.400702

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "1e81f3f1c86c"
down_revision: Union[str, Sequence[str], None] = "21355cefc333"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("admin_id", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("admin_id"),
    )
    op.create_index(op.f("ix_admins_id"), "admins", ["id"], unique=False)
    op.add_column(
        "chats",
        sa.Column(
            "last_activity",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.drop_constraint(op.f("users_admin_id_key"), "users", type_="unique")
    op.drop_column("users", "admin_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("admin_id", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_unique_constraint(
        op.f("users_admin_id_key"),
        "users",
        ["admin_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("chats", "last_activity")
    op.drop_index(op.f("ix_admins_id"), table_name="admins")
    op.drop_table("admins")
    # ### end Alembic commands ###
