"""fix cascade delete

Revision ID: 444784996cd8
Revises: 1e5ccdf3ba81
Create Date: 2026-05-29 01:08:10.620163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '444784996cd8'
down_revision: Union[str, Sequence[str], None] = '1e5ccdf3ba81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('text_conversations_chat_id_fkey'), 'text_conversations', type_='foreignkey')
    op.create_foreign_key(None, 'text_conversations', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'text_conversations', type_='foreignkey')
    op.create_foreign_key(op.f('text_conversations_chat_id_fkey'), 'text_conversations', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###
