"""added ai analytics fields

Revision ID: 4c48d205546d
Revises: f859108af9f6
Create Date: 2026-05-23 15:46:21.308608

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4c48d205546d"
down_revision: Union[str, Sequence[str], None] = "f859108af9f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("metrics", sa.Column("ai_module", sa.String(), nullable=True))
    op.add_column("metrics", sa.Column("latency", sa.Float(), nullable=True))
    op.add_column("metrics", sa.Column("created_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("metrics", "created_at")
    op.drop_column("metrics", "latency")
    op.drop_column("metrics", "ai_module")
    # ### end Alembic commands ###
