"""added admin_id to users

Revision ID: 6cbd9269144f
Revises: 1e81f3f1c86c
Create Date: 2026-05-23 14:31:00.968370

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6cbd9269144f"
down_revision: Union[str, Sequence[str], None] = "1e81f3f1c86c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("admin_id", sa.String(), nullable=True))
    op.create_unique_constraint(None, "users", ["admin_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "admin_id")
    # ### end Alembic commands ###
