"""removed admin_id from users

Revision ID: f859108af9f6
Revises: 6cbd9269144f
Create Date: 2026-05-23 14:54:44.843720

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f859108af9f6"
down_revision: Union[str, Sequence[str], None] = "6cbd9269144f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("users_admin_id_key"), "users", type_="unique")
    op.drop_column("users", "admin_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("admin_id", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_unique_constraint(
        op.f("users_admin_id_key"),
        "users",
        ["admin_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
