"""enhanced metrics table

Revision ID: fe04577dbcb4
Revises: 4c48d205546d
Create Date: 2026-05-23 16:02:02.500275

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "fe04577dbcb4"
down_revision: Union[str, Sequence[str], None] = "4c48d205546d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("metrics", sa.Column("user_id", sa.Integer(), nullable=True))
    op.add_column("metrics", sa.Column("session_id", sa.String(), nullable=True))
    op.add_column("metrics", sa.Column("estimated_cost", sa.Float(), nullable=True))
    op.add_column("metrics", sa.Column("load_score", sa.Float(), nullable=True))
    op.add_column("metrics", sa.Column("ping_ms", sa.Float(), nullable=True))
    op.alter_column("metrics", "ai_module", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_constraint(op.f("metrics_media_id_fkey"), "metrics", type_="foreignkey")
    op.drop_column("metrics", "media_id")
    op.drop_column("metrics", "caption_time")
    op.drop_column("metrics", "processing_time")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "metrics",
        sa.Column(
            "processing_time",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "metrics",
        sa.Column(
            "caption_time",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "metrics",
        sa.Column("media_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("metrics_media_id_fkey"), "metrics", "media", ["media_id"], ["id"]
    )
    op.alter_column("metrics", "ai_module", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("metrics", "ping_ms")
    op.drop_column("metrics", "load_score")
    op.drop_column("metrics", "estimated_cost")
    op.drop_column("metrics", "session_id")
    op.drop_column("metrics", "user_id")
    # ### end Alembic commands ###
